prompt="""
$character
"""

add_newline = true

[character]
error_symbol              = '[λ](#50fa7b)'
success_symbol            = '[λ](#50fa7b)'
vimcmd_symbol             = '[λ](#50fa7b)'
vimcmd_replace_one_symbol = '[λ](#50fa7b)'
vimcmd_replace_symbol     = '[λ](#50fa7b)'
vimcmd_visual_symbol      = '[λ](#50fa7b)'


# Disable all modules for transient prompt

[aws]
disabled = true

[battery]
disabled = true

[cmake]
disabled = true

[cmd_duration]
disabled = true

[cobol]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[directory]
disabled = true

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_metrics]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true

[golang]
disabled = true

[helm]
disabled = true

[hg_branch]
disabled = true

[hostname]
disabled = true

[java]
disabled = true

[jobs]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[line_break]
disabled = true

[lua]
disabled = true

[memory_usage]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[red]
disabled = true

[rlang]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[shell]
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[status]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[time]
disabled = true

[username]
disabled = true

[vagrant]
disabled = true

[vcsh]
disabled = true

[vlang]
disabled = true

[zig]
disabled = true